<?php 
echo $this->doctype(); ?>

<html lang="pt-BR" ng-app="app">
    <head>
        <meta charset="utf-8">
        <base href="<?php echo $this->basePath(); ?>" />
        <?php 
        
        echo $this->headTitle($this->translate("Nome do projeto"))
                ->setSeparator(' - ')->setAutoEscape(false);  
                
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
       
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/icons/favicon.ico'))        
                ->prependStylesheet($this->basePath('css/dataTables.bootstrap.css'))
                ->prependStylesheet($this->basePath('css/style.css'))            
                ->prependStylesheet('/lib_make_model/styles-front.css')
                ->prependStylesheet($this->basePath('css/jquery-ui.css'))
                ->prependStylesheet('/lib_make_model/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')
                ->prependStylesheet('/lib_make_model/plugins/daterangepicker/daterangepicker-bs3.css')
                ->prependStylesheet('/lib_make_model/plugins/datepicker/datepicker3.css')
                ->prependStylesheet('/lib_make_model/plugins/jvectormap/jquery-jvectormap-1.2.2.css')
                ->prependStylesheet('/lib_make_model/plugins/morris/morris.css')
                ->prependStylesheet('/lib_make_model/plugins/iCheck/flat/blue.css')
                ->prependStylesheet('/lib_make_model/dist/css/skins/_all.css')
                ->prependStylesheet('/lib_make_model/dist/css/skins/_all-skins.min.css')
                ->prependStylesheet('/lib_make_model/dist/css/AdminLTE.min.css')
                ->prependStylesheet('https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css')
                ->prependStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath('/vendor/bootstrap/bootstrap.min.css'));            

        echo $this->headScript()->prependFile($this->basePath('/lib_make_model/dist/js/demo.js'))          
                ->prependFile($this->basePath('js/jquery.dataTables.min.js'))
                ->prependFile($this->basePath('js/geral.js'))
                ->prependFile($this->basePath('js/jquery.maskedinput.js'))
                ->prependFile($this->basePath('/lib_make_model/dist/js/app.min.js'))  
                ->prependFile($this->basePath('/lib_make_model/plugins/fastclick/fastclick.min.js'))
                ->prependFile($this->basePath('/lib_make_model/plugins/slimScroll/jquery.slimscroll.min.js'))
                ->prependFile($this->basePath('/lib_make_model/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'))
                ->prependFile($this->basePath('/lib_make_model/plugins/datepicker/bootstrap-datepicker.js'))
                ->prependFile($this->basePath('/lib_make_model/plugins/daterangepicker/daterangepicker.js'))
                ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js')
                ->prependFile($this->basePath('/lib_make_model/plugins/knob/jquery.knob.js'))                
                ->prependFile($this->basePath('/lib_make_model/plugins/jvectormap/jquery-jvectormap-world-mill-en.js'))
                ->prependFile($this->basePath('/lib_make_model/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'))
                ->prependFile($this->basePath('/lib_make_model/plugins/sparkline/jquery.sparkline.min.js'))                 
                ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js')     
                ->prependFile($this->basePath('js/bootbox.js'))
                ->prependFile('/js/bootstrap.min.js')
                ->prependFile($this->basePath('js/jquery.inputmask.date.extensions.js'))
                ->prependFile($this->basePath('js/jquery.inputmask.js'))
                ->prependFile($this->basePath('js/jquery.maskMoney.js'))
                ->prependFile($this->basePath('js/jquery-ui.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'));
        
              
     ?>
        <script>
          $.widget.bridge('uibutton', $.ui.button);
        </script>
        
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">
		
			<header class="main-header">

                <a href="/" class="logo">
                  <span class="logo-mini"><b>M</b>A</span>
                  <span class="logo-lg"><b>Marca </b>marca</span>
                </a>

                <nav class="navbar navbar-static-top" role="navigation">
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    	<span class="sr-only">Toggle navigation</span>
                    </a>    
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <!-- User Account: style can be found in dropdown.less -->
                            <li class="dropdown user user-menu ">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                    <img src="img/clientes/sem_imagem.jpg" class="user-image" alt="User Image">
                                    <span class="hidden-xs">Usuário</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <!-- User image -->
                                    <li class="user-header">
                                        <img src="img/clientes/sem_imagem.jpg" class="img-circle" alt="User Image">
                                        <p>                                       
                                        	<small>Membro desde 11/05/2016</small>
                                        </p>
                                    </li>
                                    <!-- Menu Body -->
                                    <li style="display:none" class="user-body">
                                        <div class="col-xs-4 text-center">
                                        	<a href="#">Followers</a>
                                        </div>
                                        <div class="col-xs-4 text-center">
                                        	<a href="#">Sales</a>
                                        </div>
                                        <div class="col-xs-4 text-center">
                                        	<a href="#">Friends</a>
                                        </div>
                                    </li>
                                    <!-- Menu Footer-->
                                    <li class="user-footer">
                                        <div class="pull-left">
                                        	<a href="/admin/users/edit/2" class="btn btn-default btn-flat">Informações</a>
                                        </div>
                                        <div class="pull-right">
                                        	<a href="/auth/logout" class="btn btn-default btn-flat">Deslogar</a>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>      
        		</nav>
        		
      		</header>
   
      		<aside class="main-sidebar">
      
                <section class="sidebar">
                    <div class="user-panel">
                        <div class="pull-left image">
                        	<img src="img/clientes/sem_imagem.jpg" class="img-circle" alt="User Image">
                        </div>
                        <div class="pull-left info">
                            <p>Nome Usuário</p>
                            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                        </div>
                    </div>
                  <form style="display:none" action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                      <input type="text" name="q" class="form-control" placeholder="Pesquisar...">
                      <span class="input-group-btn">
                        <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
                      </span>
                    </div>
                  </form>
        
                  <ul class="sidebar-menu">
                    
                    <li class="header">MENU PRINCIPAL</li>
                    
                    <li class="active treeview">
                      
                      <a href="#">
                        <i class="fa fa-dashboard"></i> <span>Cadastros</span> <i class="fa fa-angle-left pull-right"></i>
                      </a>
                      
                      <ul class="treeview-menu">                      	
                        <li>
                        	<a href="/admin/users">
                        		<i class="fa fa-user"></i> Clientes
                    		</a>
                    	</li>                      	
                      </ul>
                      
                    </li>  
                    <li class="treeview">
                      
                      <a href="#">
                        <i class="fa  fa-book"></i> <span>Outra Modalidade</span> <i class="fa fa-angle-left pull-right"></i>
                      </a>
                      
                      <ul class="treeview-menu">                      	
                      		<li>
                            	<a href="/cursos">
                            		<i class="fa fa-random"></i> Segundo Módulo
                        		</a>
                    		</li>                      	                     	        
                      </ul>
                      
                    </li>  
                    <li>
                    	<a href="http://www.google.com/">
                    		<i class="fa fa-desktop text-aqua"></i> <span>Sem Menu</span>
                		</a>
            		</li>
                    
                  </ul>
                  
                </section>
        
      		</aside>      

        	<div class="content-wrapper">
        		<?php    	
        		echo $this->content;         		
        		?>
        	</div>		

            <footer class="main-footer">
                <div class="pull-right hidden-xs">
                	<b>Todos os Direitos Reservados. CNPJ: 00.000.000/0000-00</b>
                </div>
                <strong><a href="http://www.google.com/">© Nome da Empresa 2015 - 2016.</a></strong>
            </footer>
			<script src="<?=$this->basePath('/lib_make_model/plugins/morris/morris.min.js')?>"></script>
			<script src="<?=$this->basePath('/lib_make_model/dist/js/pages/dashboard.js')?>"></script>			
  		</div>
	</body>
</html>