<section class="content-header">
    <h1>
    	Dashboard
    	<small>Painel de Controle</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/admin"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
    </ol>
</section>
<section class="content">
    <div class="container">
    	<div class="row">
            <div class="col-md-12 flashMessages">
                        <?php 
                 $flash  =  $this->flashMessenger (); 
                 echo  $flash -> render ( 'error' ,    array ( 'alert' ,  'alert-dismissible' ,  'alert-danger' )); 
                 echo  $flash -> render ( 'info' ,     array ( 'alert' ,  'alert-dismissible' ,  'alert-info' )); 
                 echo  $flash -> render ( 'default' ,  array ( 'alert' ,  'alert-dismissible' ,  'alert-warning' )); 
                 echo  $flash -> render ( 'success' ,  array ( 'alert' ,  'alert-dismissible' ,  'alert-success' ));
                
                 ?>
            </div>
    	</div>
    </div>
    <br />   
	<div class="row">
		<div class="col-md-12">
            <div class="box box-solid">
                <div class="box-header with-border">
                	<h3 class="box-title">Box</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    Box Example
                </div><!-- /.box-body -->
            </div>
		</div>
	</div>
	<br />		
</section>

